// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCss8HnMFLMxBGC2gNNRCSAU3aQLpG2_-0',
    appId: '1:927455723217:web:4472d16c88b8f675494ff0',
    messagingSenderId: '927455723217',
    projectId: 'railsaathi-6ecca',
    authDomain: 'railsaathi-6ecca.firebaseapp.com',
    storageBucket: 'railsaathi-6ecca.appspot.com',
    measurementId: 'G-FE0K3GD9YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ljFkEpMMlXp1tLAmmEAD1Z2g86Apbiw',
    appId: '1:927455723217:android:4a4b3e7e84d88d03494ff0',
    messagingSenderId: '927455723217',
    projectId: 'railsaathi-6ecca',
    storageBucket: 'railsaathi-6ecca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYbe3IK0VajLYRd_5WlDTPGpzyHTVzcGs',
    appId: '1:927455723217:ios:13d4b3fe8a6164aa494ff0',
    messagingSenderId: '927455723217',
    projectId: 'railsaathi-6ecca',
    storageBucket: 'railsaathi-6ecca.appspot.com',
    iosBundleId: 'com.example.railsaathi',
  );
}
